---
- name: Install php and its dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ php_pkgs }}"
  become: yes

- name: Enable php fpm service
  service: 
    name: php{{ php_fpm_version }}-fpm 
    enabled: yes
  become: yes