---
# tasks file for nginx

- name: Update apt cache
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  become: yes

- name: Install nginx
  apt: 
    name: nginx 
    state: present
  become: yes

- name: Copy nginx configuration for wordpress
  template: 
    src: seera.conf
    dest: /etc/nginx/conf.d/seera.conf
  become: yes
  notify: restart nginx
