# WordPress database settings
wp_db_name: wordpress
wp_db_user: wordpress_username
wp_db_password: wordpress_password

auto_up_disable: true
core_update_level: true

# WordPress Version
wp_version: 5.2.2